### ISSUE TITLE
not working in anki  ⁨2.1.47

### ISSUE THREAD

**Issue by feghakim** [HelenFoster/AnkiSpreadsheetImportPlus#6]
This message is displayed when loading:

When loading '⁨Spreadsheet Import Plus⁩':
⁨Traceback (most recent call last):
  File "aqt\addons.py", line 230, in loadAddons
  File "C:\Users\Hakim\AppData\Roaming\Anki2\addons21\716643677\__init__.py", line 21, in <module>
    reg.register(again=False)
  File "C:\Users\Hakim\AppData\Roaming\Anki2\addons21\716643677\reg.py", line 26, in register
    importing.Importers += importer
AttributeError: module 'anki.importing' has no attribute 'Importers'

**Comment by CommanderPho** [comment]
I'm encountering the same issue with Anki 2.1.49 and the latest version of the plugin.

![2022-01-12 - Screenshot  17 14 04](https://user-images.githubusercontent.com/962210/149231466-db5d964d-4e7f-47b8-8d3c-a52045e40186.png)
 
The information from Help > About Anki > Copy Debug Info:

>     Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
>     Platform: Windows 10
>     Flags: frz=True ao=True sv=2
>     Add-ons, last update check: 2022-01-12 16:37:39
>     
>     
>     ===Add-ons (active)===
>     (add-on provided name [Add-on folder, installed at, version, is config changed])
>     Spreadsheet Import Plus ['716643677', 2020-05-11T11:31, 'None', '']
>     
>     ===IDs of active AnkiWeb add-ons===
>     716643677
>     
>     ===Add-ons (inactive)===
>     (add-on provided name [Add-on folder, installed at, version, is config changed])
>     
>

**Comment by CommanderPho** [comment]
I've implemented a fix in my pull request #8 
You may fetch this branch to try out the changes. I hope it helps.

**Comment by HelenFoster** [comment]
Fixed!
